name: Publish to Comfy Registry

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "pyproject.toml"

permissions:
  contents: read

jobs:
  publish-node:
    name: Publish Custom Node to registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Publish Custom Node
        uses: Comfy-Org/publish-node-action@d2366e7abb6ab16f3bb03e3520ae25c8cf749bc9 # main (取得日: 2026-09-11)
        with:
          personal_access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
